sonar.projectKey=Ttotest_UrbanHub
sonar.projectName=UrbanHub MS6 Validateur
sonar.organization=ttotest
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.python.coverage.reportPaths=03_rapport_tests/coverage.xml
sonar.python.xunit.reportPath=03_rapport_tests/rapport_tests.xml
sonar.coverage.exclusions=tests/**
sonar.exclusions=03_rapport_tests/**,04_analyse_avant/**,05_analyse_apres/**,06_synthese/**,*.txt,*.md
